% Auto-generated by cameraCalibrator app on 16-Feb-2024
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image26.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image27.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image42.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image44.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image45.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image49.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image51.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image52.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image53.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image55.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image60.png',...
    '/home/cmfrench/Documents/rbe3001/LabGit/RBE3001_C24_Team10/camera_calibration/Image61.png',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames, 'HighDistortion', true);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 25;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera using fisheye parameters
[cameraParams, imagesUsed, estimationErrors] = estimateFisheyeParameters(imagePoints, worldPoints, ...
    [mrows, ncols], ...
    'EstimateAlignment', false, ...
    'WorldUnits', 'millimeters');

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortFisheyeImage(originalImage, cameraParams.Intrinsics);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
